[package]
name = "tesseract-sync-committee"
version = "0.1.0"
edition = "2021"
description = "Sync-committee primitives for ISMP messaging relay"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
prover = { package = "sync-committee-prover", git = "https://github.com/polytope-labs/sync-committee-rs", branch = "main" }
verifier = { package = "sync-committee-verifier", git = "https://github.com/polytope-labs/sync-committee-rs", branch = "main" }
primitives = { package = "sync-committee-primitives", git = "https://github.com/polytope-labs/sync-committee-rs", branch = "main" }
consensus-client = { package = "ismp-sync-committee", git = "ssh://git@github.com/polytope-labs/hyperbridge", branch = "main" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.105"
hex = "0.4.3"
log = "0.4.19"
anyhow = "1.0.75"
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
futures = "0.3.28"
async-trait = "0.1.71"
tokio = { version = "1.27.0", features = ["full"] }
tokio-stream = "0.1.14"
hex-literal = "0.4.1"
base2 = "0.3.1"
primitive-types = { version = "0.12.1", features = ["impl-codec"] }
reqwest-eventsource = "0.4.0"

ismp = { git = "https://github.com/polytope-labs/ismp-rs", branch = "main" }
tesseract-primitives = { path = "../../primitives" }
tesseract-evm = { path = "../evm"}

[features]
goerli = ["consensus-client/goerli"]
mainnet = ["consensus-client/mainnet"]