[workspace]
resolver = "2"
members = [
    "arb-host",
    "op-host",
    "beefy",
    "beefy/zk",
    "bsc",
    "integration-tests",
    "sync-committee",
    "grandpa",
    "relayer",
]

[profile.release]
panic = "unwind"
opt-level = 3

[workspace.dependencies]
tracing = "0.1.40"
hex = "0.4.3"

frame-support = { version = "37.0.0" }
sp-io = { version = "38.0.0" }
sp-core = { version = "34.0.0" }
sp-consensus-beefy = { version = "22.1.0" }
sp-keyring = "39.0.0"
sp-crypto-hashing = "0.1.0"
primitive-types = { version = "0.12.2" }
sc-service = "0.46.0"
sp-runtime = { version = "39.0.5" }
sp-mmr-primitives = { version = "34.1.0" }
polkadot-core-primitives = { version = "15.0.0" }

ethers = { git = "https://github.com/polytope-labs/ethers-rs", rev = "45239225c50247e049892125d281442c084a2a92", features = ["ethers-solc"] }
ethers-contract-abigen = { git = "https://github.com/polytope-labs/ethers-rs", rev = "45239225c50247e049892125d281442c084a2a92" }
merkle-mountain-range = { package = "ckb-merkle-mountain-range", version = "0.5.2" }

# hyperbridge
beefy-verifier-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
beefy-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

polygon-pos-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
polygon-pos-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
ismp-polygon-pos = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

sync-committee-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
sync-committee-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
sync-committee-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
ismp-sync-committee = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
arbitrum-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
op-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
evm-common = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

bsc-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
bsc-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
ismp-bsc = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

grandpa-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
grandpa-verifier-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
ismp-grandpa = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

ismp = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
pallet-ismp = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
pallet-ismp-rpc = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
ismp-solidity-abi = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
geth-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
mmr-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
pallet-ismp-demo = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

subxt-utils = { git ="https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
serde-hex-utils = { git ="https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
pallet-mmr = { version = "37.0.0" }
substrate-state-machine = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
ismp-testsuite = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

# tesseract
tesseract-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
tesseract-messaging = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
transaction-fees = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
tesseract-config = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
tesseract-substrate = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }
tesseract-evm = { git = "https://github.com/polytope-labs/hyperbridge", rev = "97c170d3ded78c129ee0b81df1214de095979b0c" }

sp1-beefy = { git = "ssh://git@github.com/polytope-labs/sp1-beefy.git", rev = "2bf78874685560ca2b623594699dfa4daa2f3342" }
sp1-beefy-primitives = { git = "ssh://git@github.com/polytope-labs/sp1-beefy.git", rev = "2bf78874685560ca2b623594699dfa4daa2f3342" }

rsmq_async = { git = "https://github.com/polytope-labs/rsmq-async-rs.git", rev = "564f0af49e1a82ec8fb4dbb739eade5a7486b674" }

tesseract-beefy = { path = "./beefy" }
tesseract-sync-committee = { path = "./sync-committee" }
tesseract-grandpa = { path = "./grandpa" }
arb-host = { path = "./arb-host"}
op-host = { path = "./op-host" }
tesseract-bsc = { path = "./bsc" }
tesseract-integration-tests = { path = "./integration-tests" }
tesseract = { path = "./relayer" }

alloy-rlp = { version = "0.3.7" }
alloy-rlp-derive = "0.3.7"
alloy-sol-macro = "0.7.7"
alloy-sol-types = { version = "0.7.7" }

[workspace.dependencies.alloy-primitives]
version = "0.7.7"
default-features = false
features = ["rlp"]
