[workspace]
resolver = "2"
members = [
    "primitives",
    "consensus",
    "messaging",
    "substrate/common",
    "substrate/parachain",
#    "substrate/grandpa",
    "substrate/beefy/host",
    "relayer",
    "integration-tests",
    "ethereum/sync-committee",
    "ethereum/evm",
    "ethereum/bnb-pos",
    "payments",
    "payments/prisma-cli"
]

[profile.release]
panic = "unwind"
opt-level = 3



[workspace.dependencies]
# wasm
frame-benchmarking = { version = "25.0.0" }
frame-executive = { version = "25.0.0" }
frame-support = { version = "25.0.0" }
frame-system = { version = "25.0.0" }
frame-system-benchmarking = { version = "25.0.0" }
frame-system-rpc-runtime-api = { version = "23.0.0" }
frame-try-runtime = { version = "0.31.0" }
pallet-aura = { version = "24.0.0" }
pallet-authorship = { version = "25.0.0" }
pallet-balances = { version = "25.0.0" }
pallet-session = { version = "25.0.0" }
pallet-sudo = { version = "25.0.0" }
pallet-timestamp = { version = "24.0.0" }
pallet-transaction-payment = { version = "25.0.0" }
pallet-transaction-payment-rpc-runtime-api = { version = "25.0.0" }
pallet-message-queue = { version = "28.0.0" }
sp-api = { version = "23.0.0" }
sp-blockchain = { version = "25.0.0" }
sp-io = { version = "27.0.0" }
sp-trie = { version = "26.0.0" }
sp-block-builder = { version = "23.0.0" }
sp-consensus-aura = { version = "0.29.0" }
beefy-primitives = { package = "sp-consensus-beefy", version = "10.0.0" }
sp-core = { version = "25.0.0" }
sp-inherents = { version = "23.0.0" }
sp-offchain = { version = "23.0.0" }
sp-runtime = { version = "28.0.0" }
sp-session = { version = "24.0.0" }
sp-std = { version = "11.0.0" }
sp-transaction-pool = { version = "23.0.0" }
sp-version = { version = "26.0.0" }
sp-genesis-builder = { version = "0.4.0" }
pallet-xcm = { version = "4.0.0" }
polkadot-parachain-primitives = { version = "3.0.0" }
polkadot-runtime-common = { version = "4.0.0" }
staging-xcm = { version = "4.0.0" }
staging-xcm-builder = { version = "4.0.0" }
staging-xcm-executor = { version = "4.0.0" }
cumulus-pallet-session-benchmarking = { version = "6.0.0" }
cumulus-pallet-aura-ext = { version = "0.4.0" }
cumulus-pallet-dmp-queue = { version = "0.4.0" }
cumulus-pallet-parachain-system = { version = "0.4.0" }
cumulus-pallet-xcm = { version = "0.4.0" }
cumulus-pallet-xcmp-queue = { version = "0.4.0" }
cumulus-primitives-core = { version = "0.4.0" }
cumulus-primitives-timestamp = { version = "0.4.0" }
cumulus-primitives-utility = { version = "0.4.0" }
pallet-collator-selection = { version = "6.0.0" }
parachain-info = { package = "staging-parachain-info", version = "0.4.0" }
parachains-common = { version = "4.0.0"  }
sp-timestamp = { version = "23.0.0" }
sp-keystore = { version = "0.31.0" }
sp-mmr-primitives = { version = "23.0.0" }
sp-storage =  { version = "16.0.0" }
pallet-beefy-mmr = { version = "25.0.0" }
pallet-mmr = { version = "24.0.0" }

# client
frame-benchmarking-cli = "29.0.0"
pallet-transaction-payment-rpc = "27.0.0"
sc-basic-authorship = "0.31.0"
sc-chain-spec = "24.0.0"
sc-cli = "0.33.0"
sc-client-api = "25.0.0"
sc-consensus = "0.30.0"
sc-executor = "0.29.0"
sc-network = "0.31.0"
sc-network-sync = "0.30.0"
sc-network-common = "0.30.0"
sc-rpc = "26.0.0"
sc-service = "0.32.0"
sc-sysinfo = "24.0.0"
sc-telemetry = "12.0.0"
sc-tracing = "25.0.0"
sc-transaction-pool = "25.0.0"
sc-transaction-pool-api = "25.0.0"
sc-offchain = "26.0.0"
substrate-frame-rpc-system = "25.0.0"
substrate-prometheus-endpoint = "0.14.0"
try-runtime-cli = "0.35.0"
polkadot-cli = "4.0.0"
polkadot-primitives = "4.0.0"
polkadot-service = "4.0.0"
cumulus-client-cli = "0.4.0"
cumulus-client-consensus-aura = "0.4.0"
cumulus-client-consensus-common = "0.4.0"
cumulus-client-network = "0.4.0"
cumulus-client-service = "0.4.0"
cumulus-primitives-parachain-inherent = "0.4.0"
cumulus-relay-chain-interface = "0.4.0"
cumulus-client-consensus-proposer = "0.4.0"
cumulus-client-collator = "0.4.0"
substrate-wasm-builder = { version = "16.0.0" }
mmr-rpc = { version = "25.0.0" }
polkadot-core-primitives = { version = "4.0.0" }

ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "594627dc1c3b490ba8f513f8f5e23d11448cbcf8", features = ["ethers-solc"] }
ethers-contract-abigen = { git = "https://github.com/gakonst/ethers-rs", rev = "594627dc1c3b490ba8f513f8f5e23d11448cbcf8" }


merkle-mountain-range = { package = "ckb-merkle-mountain-range", git = "https://github.com/polytope-labs/merkle-mountain-range", branch = "seun/simplified-mmr" }
