[workspace]
resolver = "2"
members = [
    "primitives",
    "consensus",
    "messaging",
    "substrate/common",
    "substrate/parachain",
#    "substrate/grandpa",
    "substrate/beefy",
    "relayer",
    "integration-tests",
    "ethereum/sync-committee",
    "ethereum/evm"
]

[profile.release]
panic = "unwind"
opt-level = 3
