[workspace]
resolver = "2"
members = [
    "arb-host",
    "op-host",
    "beefy",
    "beefy/zk",
    "bsc",
    "fisherman",
    "integration-tests",
    "sync-committee",
    "relayer"
]

[profile.release]
panic = "unwind"
opt-level = 3

[workspace.dependencies]
tracing = "0.1.40"


frame-support = { version = "28.0.0" }
sp-io = { version = "30.0.0" }
sp-core = { version = "28.0.0" }
sp-consensus-beefy = { version = "13.0.0" }

sp-runtime = { version = "31.0.1" }
sp-mmr-primitives = { version = "26.0.0" }
polkadot-core-primitives = { version = "7.0.0" }

ethers = { git = "https://github.com/polytope-labs/ethers-rs", rev = "a61f4fd78cd9a417c74a1609e5007e17f0f0ebb4", features = ["ethers-solc"] }
ethers-contract-abigen = { git = "https://github.com/polytope-labs/ethers-rs", rev = "a61f4fd78cd9a417c74a1609e5007e17f0f0ebb4" }
merkle-mountain-range = { package = "ckb-merkle-mountain-range", version = "0.5.2" }

# hyperbridge
beefy-verifier-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
beefy-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }

polygon-pos-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
polygon-pos-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
ismp-polygon-pos = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }

sync-committee-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
sync-committee-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
sync-committee-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
ismp-sync-committee = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
arbitrum-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
op-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
evm-common = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }

bsc-prover = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
bsc-verifier = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
ismp-bsc = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }

ismp = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
pallet-ismp = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
pallet-ismp-rpc = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
ismp-solidity-abi = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
geth-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
mmr-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
pallet-ismp-demo = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }

subxt-utils = { git ="https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
pallet-mmr = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
substrate-state-machine = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }


# tesseract
tesseract-primitives = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
tesseract-messaging = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
transaction-fees = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
tesseract-config = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
tesseract-substrate = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }
tesseract-evm = { git = "https://github.com/polytope-labs/hyperbridge", rev = "e056f69a47adddb404589cfdd9051dfa0dd3d2cf" }

tesseract-beefy = { path = "./beefy" }
tesseract-sync-committee = { path = "./sync-committee" }
arb-host = { path = "./arb-host"}
op-host = { path = "./op-host" }
tesseract-bsc = { path = "./bsc" }
tesseract-fisherman = { path = "./fisherman" }
tesseract-integration-tests = { path = "./integration-tests" }
tesseract = { path = "./relayer" }
