[package]
name = "pallet-mmr-runtime-api"
version = "0.1.1"
edition = "2021"
publish = false

[dependencies]
sp-api = { workspace = true }
sp-std = { workspace = true }
sp-core = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
codec = { workspace = true }
sp-mmr-primitives = { workspace = true }
pallet-ismp = { workspace = true }

[features]
default = ["std"]
std = [
    "sp-api/std",
    "sp-std/std",
    "codec/std",
    "serde",
    "sp-core/std",
    "sp-mmr-primitives/std",
    "pallet-ismp/std",
]
