[package]
name = "ismp-beefy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
codec = { workspace = true, features = ["derive"] }
primitive-types = { workspace = true }

ismp = { workspace = true }
beefy-verifier = { workspace = true }
pallet-ismp = { workspace = true }
substrate-state-machine = { workspace = true }

[dependencies.polkadot-sdk]
workspace = true
features = [
    "frame-support",
    "frame-system",
    "sp-trie",
    "sp-io",
    "sp-runtime",
    "sp-consensus-aura",
    "sp-core",
    "sp-std",
]

[features]
default = ["std"]
std = [
    "codec/std",
    "ismp/std",
    "polkadot-sdk/std",
    "primitive-types/std",
    "pallet-ismp/std",
    "beefy-verifier/std",
    "substrate-state-machine/std",
]

try-runtime = ["polkadot-sdk/try-runtime"]
runtime-benchmarks = [
    "polkadot-sdk/frame-benchmarking",
    "polkadot-sdk/runtime-benchmarks",
    "pallet-ismp/runtime-benchmarks",
]

