[package]
name = "xcm-runtime-integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
gargantua-runtime = { workspace = true }
rococo-runtime = { version = "24.0.0", default-features = false }


[dependencies.polkadot-sdk]
workspace = true
default-features = true
features = [
    "frame-support",
    "frame-system",
    "pallet-balances",
    "pallet-timestamp",
    "pallet-sudo",
    "sp-io",
    "sp-std",
    "sp-trie",
    "sp-runtime",
    "pallet-assets",
    "sp-state-machine",
    "xcm-simulator",
    "pallet-xcm",
    "polkadot-parachain-primitives",
    "polkadot-runtime-common",
    "staging-xcm",
    "staging-xcm-builder",
    "staging-xcm-executor",
    "polkadot-runtime-parachains",
    "pallet-message-queue",
    "parachains-common",
    "cumulus-pallet-xcm",
    "staging-parachain-info",
    "cumulus-primitives-core",
    "cumulus-pallet-xcmp-queue",
    "cumulus-pallet-parachain-system",
    "pallet-vesting",
    "pallet-collator-selection",
    "pallet-session",
    "pallet-assets-holder",
    "cumulus-primitives-parachain-inherent",
    "xcm-emulator",
    "sp-consensus-beefy",
    "cumulus-test-relay-sproof-builder",
    "polkadot-primitives",
    "sc-consensus-grandpa",
    "sp-authority-discovery",
]

[features]
default = ["std"]
std = ["polkadot-sdk/std",
    "gargantua-runtime/std",
"rococo-runtime/std"]