[package]
name = "tesseract"
version = "0.1.4"
edition = "2021"
description = "Chain agnostic relayer implementation for ISMP"
authors = ["Polytope Labs <hello@polytope.technology>"]

[dependencies]
parachain = { package = "tesseract-parachain", path = "../substrate/parachain" }
tesseract-substrate = { path = "../substrate/common" }
consensus = { package = "tesseract-consensus", path = "../consensus" }
primitives = { package = "tesseract-primitives", path = "../primitives" }
messaging = { package = "tesseract-messaging", path = "../messaging" }
tesseract-evm = { path = "../ethereum/evm" }
tesseract-sync-committee = { path = "../ethereum/sync-committee" }
tesseract-beefy = { path = "../substrate/beefy/host" }

# polytope labs
ismp = { git = "https://github.com/polytope-labs/hyperbridge", branch = "main" }
pallet-ismp = { git = "https://github.com/polytope-labs/hyperbridge", branch = "main" }
ismp-sync-committee = { git = "https://github.com/polytope-labs/hyperbridge", branch = "main" }

# crates.io
log = "0.4.19"
env_logger = "0.10.0"
anyhow = "1.0.71"
futures = "0.3.28"
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"
async-trait = "0.1.68"
clap = { version = "4.3.5", features = ["derive"] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "fs"] }
ethers = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }


[features]
sepolia = ["tesseract-sync-committee/sepolia", "tesseract-evm/sepolia"]
mainnet = ["tesseract-sync-committee/mainnet", "tesseract-evm/mainnet"]
