[package]
name = "pallet-mmr-rpc"
version = "0.1.0"
edition = "2021"
authors = ["Polytope Labs <hello@polytope.technology>"]
license = "Apache-2.0"
repository = "https://github.com/polytope-labs/hyperbridge"
homepage = "https://docs.hyperbridge.network/developers/polkadot/getting-started"
documentation = "https://docs.rs/pallet-ismp-rpc"
description = "RPC apis for pallet-ismp"
keywords = ["substrate", "polkadot-sdk", "ISMP", "interoperability"]
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = { workspace = true }
codec = { workspace = true, features = ["derive"], default-features = true }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }

sp-mmr-primitives = { workspace = true, default-features = true }
sc-client-api = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

pallet-ismp = { workspace = true, default-features = true }
pallet-ismp-rpc = { workspace = true, default-features = true }
pallet-mmr-runtime-api = { workspace = true, default-features = true }
